export const USUARIO_AUTENTICADO ="USUARIO_AUTENTICADO"
export const REGISTRO_EXITOSO ="REGISTRO_EXITOSO"
export const REGISTRO_ERROR ="REGISTRO_ERROR"
export const INICIO_SESION_ERROR ="INICIO_SESION_ERROR"
export const INICIO_SESION_EXITOSO ="INICIO_SESION_EXITOSO"
export const CERRAR_SESION ="CERRAR_SESION"

//Subir archivos
export const SUBIR_ARCHIVO_EXITOSO ="SUBIR_ARCHIVO_EXITO"
export const SUBIR_ARCHIVO_ERROR ="SUBIR_ARCHIVO_ERROR"

export const CREAR_ENLACE_EXITO="CREAR_ENLACE_EXITO"
export const CREAR_ENLACE_ERROR="CREAR_ENLACE_ERROR"

export const LIMPIAR_ALERTA ="LIMPIAR_ALERTA"
export const MOSTRAR_ALERTA ="MOSTRAR_ALERTA"
export const SUBIENDO_ARCHIVO ="SUBIENDO_ARCHIVO"

export const AGREGAR_PASSWORD ="AGREGAR_PASSWORD"
export const AGREGAR_DESCARGAS ="AGREGAR_DESCARGAS"
export const LIMPIAR_STATE ="LIMPIAR_STATE";
