import { Inter } from 'next/font/google'
import "./globals.css"
import {Header} from "../components/Header";
import AuthState from "../context/auth/authState";
import AppProvider from "../context/app/appState";

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <AuthState>
        <AppProvider>
            <body className={inter.className}>
                <div className={"bg-gray-100 min-h-screen"}>
                    <div className="container mx-auto">
                        <Header/>
                        <main className="mt-20 p-4">
                            {children}
                        </main>
                    </div>
                </div>
            </body>
        </AppProvider>
    </AuthState>
    </html>
  )
}
